"""create reviews table

Revision ID: 7e6a69bb2bf8
Revises: 2a04b6892a9f
Create Date: 2024-03-13 22:08:35.999417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6a69bb2bf8'
down_revision = '2a04b6892a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('supplierId', sa.Integer(), nullable=True),
    sa.Column('starReview', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', name='starReview_enum'), nullable=True),
    sa.Column('valueForMoney', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', name='valueForMoney_enum'), nullable=True),
    sa.Column('cleanliness', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', name='cleanliness_enum'), nullable=True),
    sa.Column('condition', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', name='condition_enum'), nullable=True),
    sa.Column('pickUpSpeed', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', name='pickUpSpeed_enum'), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
