"""create cars table

Revision ID: a2e2751494d0
Revises: ec9b6fdac873
Create Date: 2024-03-13 21:49:08.361181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e2751494d0'
down_revision = 'ec9b6fdac873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('supplierId', sa.Integer(), nullable=True),
    sa.Column('gear', sa.Enum('Manual', 'Automatic', name='gear_enum'), nullable=False),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['locationId'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
