"""Add isAdmin column to Users table

Revision ID: b66567617b87
Revises: 7e6a69bb2bf8
Create Date: 2024-04-23 22:01:24.777622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66567617b87'
down_revision = '7e6a69bb2bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.Boolean, nullable=False,server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAdmin')

    # ### end Alembic commands ###
