"""create location and pricing table

Revision ID: cee173fb2093
Revises: 4bbf8d838b9e
Create Date: 2024-03-13 15:45:04.633799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee173fb2093'
down_revision = '4bbf8d838b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('addedPrice', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('supplierId', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing')
    op.drop_table('location')
    # ### end Alembic commands ###
