"""Included & updated other models

Revision ID: ec9b6fdac873
Revises: cee173fb2093
Create Date: 2024-03-13 21:38:37.007700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9b6fdac873'
down_revision = 'cee173fb2093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('addedPrice')

    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locationId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protectionCost', sa.Numeric(scale=2), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['locationId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('protectionCost')
        batch_op.drop_column('locationId')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addedPrice', sa.NUMERIC(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
